language: objective-c
osx_image: xcode10.2
env:
- DESTINATION="OS=8.0,name=iPhone 6" SCHEME="PeriapseNetworking-Universal" SDK=iphoneos

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- gem install xcpretty --quiet

script:
- xcodebuild clean build -project PeriapseNetworking.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project PeriapseNetworking.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

