language: objective-c
osx_image: xcode10.2
env:
- DESTINATION="OS=11.0,name=iPhone 6" SCHEME="PeriapseNetworking-Universal" SDK=iphonesimulator

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- cd Framework-iOS && carthage update --platform iOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -project PeriapseNetworking.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild test -project PeriapseNetworking.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

